### ISSUE TITLE
Compatibility with gtm4wp Product ID prefix

### ISSUE THREAD

**Issue by colmtroy** [stape-io/facebook-tag#29]
This is a tricky one so hopefully I explain it correctly :)

gtm4wp (our main data layer source for a WP/Woo store) has a Product ID prefix field
![](https://i.imgur.com/2IfQt0h.png)

which is very useful to ensure gtm4wp is compatible with WooCommerce product feeds plugins like [Google Product Feed](https://woocommerce.com/products/google-product-feed/) which adds the `woocommerce_gpf_` to all products in the feeds it produces.

the gtm4wp data layer for GA4 eCommerce events then includes this prefix in the `items.id` key while preserving the original product id in the `items.item_id` key

![](https://i.imgur.com/pJNwVTD.png) 

This presents a problem for me as [your facebook capi tag will use `item_id` rather than the `id` key](https://github.com/stape-io/facebook-tag/blob/main/template.js#L381)
```
      if (d.item_id) content.id = d.item_id;
```

Rather than setting up my own custom vars/events, I was able to easily solve this by simply replacing the line above with 
```if (d.id) content.id = d.id;```

which ensures the prefixed version gets sent on to the server side.

I'd rather not have to maintain my own fork of your excellent tag :) So I'm wondering if there's some way to add an option to set which key a user would prefer to use (e.g. id vs. item_id) which would ensure no breaking changes for your other customers but also improve compatibility with most common WooCommerce extensions that produce feeds with prefixes?

Thanks.

**Comment by kHorozhanov** [comment]
@colmtroy Hi! I have added pr that added the ability to specify custom itemIdKey

**Comment by colmtroy** [comment]
@kHorozhanov fantastic! Thanks so much for that.

**Comment by daryltavernor** [comment]
I'm trying to use this feature but I don't have the necessary knowledge to implement it. Just like the request above I want to use ID from the item array. I'm not sure what key to use now that the feature has been implemented. I want to extract the key 'ID', just like the original poster. To do this what key would I add?

<img width="305" alt="Image" src="https://github.com/user-attachments/assets/ae7696fe-6de0-4659-8a33-261de0869c3e" />

I really appreciate your help on this because I think it needs how put the documentation
